import React, { useState, useRef, useMemo, useEffect } from 'react';
import { 
  GoogleMap, 
  useJsApiLoader, 
  Autocomplete, 
  DirectionsRenderer 
} from '@react-google-maps/api';
import { scoreRoutePollen } from '../api/pollen';

const GOOGLE_API_KEY = "AIzaSyD4aUoax3vID5wTcGyH1OLzyCebwclWsQ4";
const LIBRARIES = ['places'];

// Center set to San Diego initially
const defaultCenter = { lat: 32.7157, lng: -117.1611 };

// Cyperbunk tech noir base map styling
const darkMapStyles = [
  { elementType: 'geometry', stylers: [{ color: '#0f172a' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#0f172a' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#94a3b8' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#cbd5e1' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#cbd5e1' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#1e293b' }] },
  { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#64748b' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#334155' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#1e293b' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#94a3b8' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#475569' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#1e293b' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#0B0510' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#0B0510' }] },
  { featureType: 'water', elementType: 'labels.text.stroke', stylers: [{ color: '#0B0510' }] },
];

export default function Dashboard() {
  const { isLoaded } = useJsApiLoader({
    googleMapsApiKey: GOOGLE_API_KEY,
    libraries: LIBRARIES,
  });

  const [map, setMap] = useState(null);
  
  // Directions and Route evaluations
  const [directionsResponse, setDirectionsResponse] = useState(null);
  const [evaluatedRoutes, setEvaluatedRoutes] = useState([]);
  const [selectedRouteIndex, setSelectedRouteIndex] = useState(0);
  
  // UI State
  const [isCalculating, setIsCalculating] = useState(false);

  // Autocomplete Refs
  /** @type React.MutableRefObject<HTMLInputElement> */
  const originRef = useRef();
  /** @type React.MutableRefObject<HTMLInputElement> */
  const destinationRef = useRef();

  // Color selection based on Pollen UPI (1 to 5)
  const getRouteColor = (score, isSelected) => {
    if (!isSelected) return '#64748b'; // Inactive route grey
    if (score < 2) return '#4ade80'; // Emerald/Green - Safe
    if (score < 3.5) return '#facc15'; // Yellow/Amber - Moderate
    return '#ef4444'; // Red - High Hazard
  };

  const getSeverityLabel = (score) => {
    if (score < 2) return 'Clean Air';
    if (score < 3.5) return 'Moderate Pollen';
    return 'Severe Pollen Hazard';
  };

  async function calculateRoute() {
    if (originRef.current.value === '' || destinationRef.current.value === '') {
      return;
    }
    
    setIsCalculating(true);
    setDirectionsResponse(null);
    setEvaluatedRoutes([]);
    
    try {
      const directionsService = new google.maps.DirectionsService();
      
      const results = await directionsService.route({
        origin: originRef.current.value,
        destination: destinationRef.current.value,
        travelMode: google.maps.TravelMode.DRIVING,
        provideRouteAlternatives: true, // Crucial for getting multiple options
      });
      
      setDirectionsResponse(results);

      // Now iterate over each returned route and evaluate the pollen
      const evaluated = [];
      const numRoutes = results.routes.length;
      
      for (let i = 0; i < numRoutes; i++) {
        const route = results.routes[i];
        
        // Use the overview_path generated by Google to sample points
        const scoreData = await scoreRoutePollen(route.overview_path);
        
        evaluated.push({
          index: i,
          duration: route.legs[0].duration.text,
          distance: route.distance ? route.legs[0].distance.text : route.legs[0].distance.text, // Fixed
          summary: route.summary || `Route ${i + 1}`,
          pollenScore: scoreData.score,
        });
      }
      
      // Sort routes by lowest pollen score first to make the safest one index 0
      // Actually we'll keep the order but mark the "Recommended" one dynamically.
      // Wait we want user to manually pick, maybe default to fastest one (Google's default index 0)
      
      setEvaluatedRoutes(evaluated);
      
      // Auto-select the cleanest route!
      let cleanestIndex = 0;
      let minScore = Infinity;
      evaluated.forEach((rt, i) => {
         if(rt.pollenScore < minScore) {
             minScore = rt.pollenScore;
             cleanestIndex = i;
         }
      });
      setSelectedRouteIndex(cleanestIndex);
      
    } catch (err) {
      console.error("Routing error:", err);
      alert("Could not calculate routes. Check input places or API quotas.");
    } finally {
      setIsCalculating(false);
    }
  }

  function clearRoute() {
    setDirectionsResponse(null);
    setEvaluatedRoutes([]);
    originRef.current.value = '';
    destinationRef.current.value = '';
  }

  if (!isLoaded) {
    return (
      <div className="min-h-screen bg-[#0B0510] flex items-center justify-center">
        <div className="w-12 h-12 border-4 border-fuchsia-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <main className="fixed inset-0 w-full h-full bg-[#0B0510]">
      {/* ── Google Map Background ────────────────────────────────────────── */}
      <div className="absolute inset-0 z-0">
        <GoogleMap
          center={defaultCenter}
          zoom={12}
          mapContainerStyle={{ width: '100%', height: '100%' }}
          options={{
            styles: darkMapStyles,
            disableDefaultUI: true,
            zoomControl: true,
          }}
          onLoad={(map) => setMap(map)}
        >
          {directionsResponse && directionsResponse.routes.map((route, idx) => {
            const isSelected = idx === selectedRouteIndex;
            const evalData = evaluatedRoutes.find(er => er.index === idx);
            const score = evalData ? evalData.pollenScore : 0;
            const routeColor = getRouteColor(score, isSelected);
            
            return (
              <DirectionsRenderer 
                key={idx}
                directions={directionsResponse}
                routeIndex={idx}
                options={{
                  polylineOptions: {
                    zIndex: isSelected ? 50 : 10,
                    strokeColor: routeColor,
                    strokeWeight: isSelected ? 6 : 4,
                    strokeOpacity: isSelected ? 1.0 : 0.4,
                  },
                  suppressMarkers: !isSelected,
                  preserveViewport: true
                }}
              />
            )
          })}
        </GoogleMap>
      </div>

      {/* ── Overlay Control Panel ────────────────────────────────────────── */}
      <div className="absolute top-24 left-6 z-[10] w-full max-w-sm pointer-events-auto">
        <div className="bg-[#0B0510]/80 backdrop-blur-xl border border-fuchsia-500/20 shadow-[0_0_30px_rgba(0,0,0,0.8)] rounded-3xl p-6 flex flex-col gap-4">
          
          <h2 className="text-xl font-bold text-white mb-2 tracking-wide font-orbitron drop-shadow-[0_0_10px_rgba(217,70,239,0.5)]">
            Aero-Path Planner
          </h2>

          {/* Inputs */}
          <div className="flex flex-col gap-3">
            <div className="relative">
              <Autocomplete>
                 <input 
                  type="text" 
                  ref={originRef}
                  placeholder="Starting Point"
                  className="w-full bg-slate-900/60 border border-slate-700 rounded-xl pl-8 pr-4 py-3 text-sm text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-fuchsia-500 transition-colors"
                 />
              </Autocomplete>
              <div className="absolute left-[12px] top-1/2 -translate-y-1/2 w-2 h-2 rounded-full border-2 border-slate-400 bg-transparent pointer-events-none"></div>
            </div>
            
            <div className="h-4 border-l-2 border-dotted border-slate-700 ml-[-12px]"></div>
            
            <div className="relative">
              <Autocomplete>
                <input 
                  type="text" 
                  ref={destinationRef}
                  placeholder="Destination"
                  className="w-full bg-slate-900/60 border border-slate-700 rounded-xl pl-8 pr-4 py-3 text-sm text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-cyan-400 transition-colors"
                />
              </Autocomplete>
              <div className="absolute left-[12px] top-1/2 -translate-y-1/2 w-2 h-2 rounded-none border-none bg-cyan-400 pointer-events-none"></div>
            </div>
          </div>

          {/* Controls */}
          <div className="flex gap-3 mt-2">
            <button 
              onClick={calculateRoute}
              disabled={isCalculating}
              className={`flex-1 py-3 rounded-xl text-xs font-bold tracking-widest uppercase transition-all ${isCalculating ? 'bg-slate-800 text-slate-500 shadow-none cursor-not-allowed' : 'bg-fuchsia-600 text-white shadow-[0_0_20px_rgba(217,70,239,0.4)] hover:bg-fuchsia-500 hover:shadow-[0_0_30px_rgba(217,70,239,0.6)]'}`}
            >
              {isCalculating ? 'Scanning...' : 'Plot Safe Route'}
            </button>
            <button 
              onClick={clearRoute}
              className="px-4 py-3 bg-slate-800/80 border border-slate-700 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 6h18"></path><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"></path><path d="M8 6V4c0-1 1-2 2-2h4c0-1 1-2 2-2v2"></path></svg>
            </button>
          </div>
          
        </div>

        {/* ── Route Results Output ───────────────────────────────────────── */}
        {evaluatedRoutes.length > 0 && (
          <div className="mt-4 flex flex-col gap-3 max-h-[50vh] overflow-y-auto">
            {evaluatedRoutes.map((rt) => {
               const isSelected = selectedRouteIndex === rt.index;
               const colorLabel = getSeverityLabel(rt.pollenScore);
               // Derive accent from severity
               const accentColorClass = rt.pollenScore < 2 ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-400' 
                                      : rt.pollenScore < 3.5 ? 'bg-yellow-500/20 border-yellow-500/50 text-yellow-400'
                                      : 'bg-red-500/20 border-red-500/50 text-red-400';
               
               return (
                 <div 
                   key={rt.index}
                   onClick={() => setSelectedRouteIndex(rt.index)}
                   className={`p-4 rounded-2xl cursor-pointer backdrop-blur-md transition-all ${isSelected ? 'bg-slate-900/90 border-2 ' + accentColorClass.split(' ')[1] + ' shadow-lg transform scale-100 flex-1' : 'bg-slate-900/50 border border-slate-800 hover:bg-slate-900/70 scale-95 opacity-70'}`}
                 >
                    <div className="flex justify-between items-start mb-2">
                       <h3 className={`font-orbitron font-bold ${isSelected ? 'text-white' : 'text-slate-400'}`}>
                         {rt.summary}
                       </h3>
                       {isSelected && (
                          <span className={`text-[10px] px-2 py-1 rounded font-bold uppercase tracking-wider border ${accentColorClass}`}>
                            {colorLabel}
                          </span>
                       )}
                    </div>
                    
                    <div className="flex justify-between items-end">
                      <div className="text-xs text-slate-400">
                        <span className="text-slate-200 font-medium">{rt.duration}</span> • {rt.distance}
                      </div>
                      <div className="text-right">
                        <span className="text-[10px] uppercase text-slate-500 block">Avg UPI</span>
                        <span className={`font-bold tabular-nums text-lg ${accentColorClass.split(' ')[2]}`}>
                           {rt.pollenScore > 0 ? rt.pollenScore.toFixed(1) : '< 1.0'}
                        </span>
                      </div>
                    </div>
                 </div>
               )
            })}
          </div>
        )}
      </div>
      
    </main>
  );
}
